packages:
  # all packages in direct subdirs of packages/
  - "packages/**/*"
  # all packages in subdirs of components/
  - "examples/**/*"
  - "bausaurus/**"

  # exclude packages that are inside test directories
  - "!examples/aws/sst/**/*"
  - "!examples/aws/CloudFront/website-https/svelte-app"
  - "!examples/aws/Lambda/lambda-web-adapter-cdk/LambdaAdapterCdkStack-lambdaAdapterFunction*"
  - "!examples/aws/S3/s3-object-lambda/sam-app-ResizeFunction*"
  - "!examples/aws/StepFunctions/lambda-sfn/sam-app-LambdaProxy*"
