jobs:
  test:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - checkout
      - node/install:
          node-version: "14.15"
          npm-version: "6.14.8"
      - run: npm install
      - run: node --version
      - run: openssl version
      - run: npm run decrypt-data-ci
      - run: eval "$(ssh-agent -s)"
      - run: chmod 600 secrets/kp.pem
      - run: ssh-add secrets/kp.pem
      - run: ssh-add -l
      - run: sudo npm run link
      - run: mkdir /home/circleci/.aws && touch /home/circleci/.aws/credentials && touch /home/circleci/.aws/config
      - run: CONTINUOUS_INTEGRATION=1 npm test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test:
    jobs:
      - test:
        matrix:
          parameters:
            version:
              - 14.15.0
