jobs:
  test:
    docker:
      - image: "cimg/node:16.14"
    steps:
      - aws-cli/install
      - checkout
      - node/install:
          node-version: "16.14.2"
      - run: npm install
      - run: node --version
      - run: openssl version
      - run: npm run decrypt-data-ci
      - run: eval "$(ssh-agent -s)"
      - run: chmod 600 secrets/kp.pem
      - run: ssh-add secrets/kp.pem
      - run: ssh-add -l
      - run: npm run bootstrap
      - run: mkdir ~/junit
      - run: mkdir /home/circleci/.aws && touch /home/circleci/.aws/credentials && touch /home/circleci/.aws/config
      #- run: STAGE=ci MOCHA_FILE=~/junit/test-results.xml npm run test:ci
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3

version: 2.1
workflows:
  test:
    jobs:
      - test